
test_suite(
    name = "AllTests",
    tests = [
        "//submodules/MTWebSocketTransport:MTWebSocketTransportTests",
        "//submodules/TelegramUIPreferences:MessageSavingStoreTests",
        "//submodules/TextFormat:TextFormatTests",
    ],
    visibility = [
        "//visibility:public",
    ],
)
